# Gitlab CI based on their template
# this file can be used as a reference on how to build syncopoli
#
# some notes:
#
# for local ndk-bundle, download ndk and set ANDROID_NDK_HOME and ANDROID_NDK to ndk-bundle directory

image: openjdk:11-jdk

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMD_LINE_TOOLS_URL: "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
  SDK_MANAGER: sdk-tools-linux/cmdline-tools/latest/bin/sdkmanager

before_script:
  - apt-get -qq update --yes
  - apt-get -qq install --yes wget tar unzip lib32stdc++6 lib32z1 build-essential file
  - wget --quiet ${CMD_LINE_TOOLS_URL} -O tools.zip
  - unzip -qq tools.zip -d sdk-tools-linux
  - mkdir sdk-tools-linux/cmdline-tools/latest
  - mv sdk-tools-linux/cmdline-tools/* sdk-tools-linux/cmdline-tools/latest/  || true
  - yes | ${SDK_MANAGER} --licenses > /dev/null || true
  - ${SDK_MANAGER} --install ndk-bundle > /dev/null
  - yes | ${SDK_MANAGER} --licenses  > /dev/null || true
  - export ANDROID_HOME=$PWD/sdk-tools-linux
  - export PATH=$PATH:$PWD/sdk-tools-linux/platform-tools/
  - chmod +x ./gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk

unitTests:
  stage: test
  script:
    - ./gradlew test
